### PR TITLE
Implemented ability to add/remove celebrity profiles

### PR DESCRIPTION
**Pull request by jakepeyser**
Closes issue #2  - added `celebrities/add` and `celebrities/remove` endpoints to enable the ability to programmatically add and remove Twitter celebrities from the database

### CODE REVIEW

**Comment by germanattanasio** [comment]
Jake, can you make this functionality and the `/celebrities/syncdb` functionality to be unavailable when using `DEMO==true` as environment variable? We want to prevent people from using this in the demo

**Comment by germanattanasio** [comment]
you can make all the method that are changing things to be POST and only let people use post if is not the demo. that's just an idea

**Comment by jakepeyser** [comment]
Sure thing, I can make that change and add another commit

**Comment by jakepeyser** [comment]
Made `celebrities/syncdb` `celebrities/add` and `celebrities/remove` all POST requests and forbidding calls to any POST request under `celebrities` route when the env var `DEMO === 1`. Looks fine locally and in my Bluemix space, but I recommend testing with your setup on Bluemix before you push up to the live demo

**Comment by germanattanasio** [comment]
cool! thanks Jake!

**Comment by germanattanasio** [comment]
@jzhang300 can you give it a try ?

**Comment by jzhang300** [comment]
I'm looking right now

**Pull request merged**
