### PR TITLE
Added Loading Page

### PR DESCRIPTION
**Pull request by karentycoon**
When we show the demo on conferences,  we found one problem. After user clicks the "Match Me" button, the webpage stays same and user does not have an idea of what's happening. So we made this modification. When user clicks the "Match Me" button, it will show a page saying "Your Celebrity Match is extracting your tweets or instagram images you posted to predict your personality........." along with explanation of how things work. In this way, if user entered an account that is not cached in db thus need to wait for long time, the user can read the explanations and know what will happen instead of just waiting at the index page.

### CODE REVIEW

**Comment by germanattanasio** [comment]
can you take a picture/gif so that I can see how the changes look like ?

**Comment by karentycoon** [comment]
@germanattanasio Please see this video to see how loading page looks like https://youtu.be/P4TnRyT5Z1k

**Comment by germanattanasio** [comment]
Hey, looks like there is an instagram button now. What's the deal with that? I don't think we want to add support for instagram now.

**Comment by karentycoon** [comment]
@germanattanasio  I sent you an email to explain this. Please take a look at it. Thanks!

**Comment by germanattanasio** [comment]
I saw the email. Can you get some help on the UI part? the demo was designed to be use with Twitter and I don't like the way that the new UI with the instragram button looks like.

**Pull request closed without merging**
